
export class Tiendas {

    lista = [
        {code: "0",nombre: "CENTRAL",user: "lm000",password: "000lm",token: ""}, 
        {
            code: "2",
            nombre: "ALBORAYA",
            user: "lm002",
            password: "002lm",
            token: ""
        }, {
            code: "4",
            nombre: "LAS ROZAS",
            user: "lm004",
            password: "004lm",
            token: ""
        }, {
            code: "5",
            nombre: "UTEBO",
            user: "lm005",
            password: "005lm",
            token: ""
        }, {
            code: "6",
            nombre: "MARRATXI-MALLORCA",
            user: "lm006",
            password: "006lm",
            token: ""
        }, {
            code: "7",
            nombre: "ALCORCON",
            user: "lm007",
            password: "007lm",
            token: ""
        }, {
            code: "8",
            nombre: "MALIANO-SANTANDER",
            user: "lm008",
            password: "008lm",
            token: ""
        }, {
            code: "9",
            nombre: "TOMARES",
            user: "lm009",
            password: "009lm",
            token: ""
        }, {
            code: "10",
            nombre: "LA LAGUNA-TENERIFE",
            user: "lm010",
            password: "010lm",
            token: ""
        }, {
            code: "11",
            nombre: "ALCALA DE HENARES",
            user: "lm011",
            password: "011lm",
            token: ""
        }, {
            code: "12",
            nombre: "TARRAGONA",
            user: "lm012",
            password: "012lm",
            token: ""
        }, {
            code: "13",
            nombre: "SANT BOI",
            user: "lm013",
            password: "013lm",
            token: ""
        }, {
            code: "14",
            nombre: "MARBELLA",
            user: "lm014",
            password: "014lm",
            token: ""
        }, {
            code: "15",
            nombre: "JEREZ",
            user: "lm015",
            password: "015lm",
            token: ""
        }, {
            code: "16",
            nombre: "S.S. DE LOS REYES",
            user: "lm016",
            password: "016lm",
            token: ""
        }, {
            code: "17",
            nombre: "TELDE",
            user: "lm017",
            password: "017lm",
            token: ""
        }, {
            code: "18",
            nombre: "LLANERA-OVIEDO",
            user: "lm018",
            password: "018lm",
            token: ""
        }, {
            code: "19",
            nombre: "ALDAIA",
            user: "lm019",
            password: "019lm",
            token: ""
        }, {
            code: "20",
            nombre: "PAMPLONA",
            user: "lm020",
            password: "020lm",
            token: ""
        }, {
            code: "21",
            nombre: "ALICANTE",
            user: "lm021",
            password: "021lm",
            token: ""
        }, {
            code: "22",
            nombre: "LOS BARRIOS",
            user: "lm022",
            password: "022lm",
            token: ""
        }, {
            code: "24",
            nombre: "ROQUETAS DE MAR",
            user: "lm024",
            password: "024lm",
            token: ""
        }, {
            code: "25",
            nombre: "LA OROTAVA",
            user: "lm025",
            password: "025lm",
            token: ""
        }, {
            code: "27",
            nombre: "VITORIA",
            user: "lm027",
            password: "027lm",
            token: ""
        }, {
            code: "28",
            nombre: "CASTELLON",
            user: "lm028",
            password: "028lm",
            token: ""
        }, {
            code: "29",
            nombre: "MASSANASSA",
            user: "lm029",
            password: "029lm",
            token: ""
        }, {
            code: "33",
            nombre: "BADALONA",
            user: "lm033",
            password: "033lm",
            token: ""
        }, {
            code: "34",
            nombre: "SANTIAGO",
            user: "lm034",
            password: "034lm",
            token: ""
        }, {
            code: "35",
            nombre: "BARAKALDO",
            user: "lm035",
            password: "035lm",
            token: ""
        }, {
            code: "36",
            nombre: "MALAGA",
            user: "lm036",
            password: "036lm",
            token: ""
        }, {
            code: "37",
            nombre: "SALAMANCA",
            user: "lm037",
            password: "037lm",
            token: ""
        }, {
            code: "38",
            nombre: "PALMA CIUDAD",
            user: "lm038",
            password: "038lm",
            token: ""
        }, {
            code: "39",
            nombre: "LEGANES2",
            user: "lm039",
            password: "039lm",
            token: ""
        }, {
            code: "40",
            nombre: "CARTAGENA",
            user: "lm040",
            password: "040lm",
            token: ""
        }, {
            code: "41",
            nombre: "MURCIA",
            user: "lm041",
            password: "041lm",
            token: ""
        }, {
            code: "42",
            nombre: "PUERTO REAL",
            user: "lm042",
            password: "042lm",
            token: ""
        }, {
            code: "43",
            nombre: "GRANADA",
            user: "lm043",
            password: "043lm",
            token: ""
        }, {
            code: "44",
            nombre: "VALENCIA OESTE",
            user: "lm044",
            password: "044lm",
            token: ""
        }, {
            code: "45",
            nombre: "RIVAS2",
            user: "lm045",
            password: "045lm",
            token: ""
        }, {
            code: "46",
            nombre: "GETAFE2",
            user: "lm046",
            password: "046lm",
            token: ""
        }, {
            code: "47",
            nombre: "GANDIA",
            user: "lm047",
            password: "047lm",
            token: ""
        }, {
            code: "48",
            nombre: "TAMARACEITE",
            user: "lm048",
            password: "048lm",
            token: ""
        }, {
            code: "49",
            nombre: "SEVILLA ALCALA",
            user: "lm049",
            password: "049lm",
            token: ""
        }, {
            code: "50",
            nombre: "BARAJAS",
            user: "lm050",
            password: "050lm",
            token: ""
        }, {
            code: "51",
            nombre: "PUERTO VENECIA",
            user: "lm051",
            password: "051lm",
            token: ""
        }, {
            code: "52",
            nombre: "GIJON",
            user: "lm052",
            password: "052lm",
            token: ""
        }, {
            code: "53",
            nombre: "OIARZUN",
            user: "lm053",
            password: "053lm",
            token: ""
        }, {
            code: "54",
            nombre: "HUELVA2",
            user: "lm054",
            password: "054lm",
            token: ""
        }, {
            code: "56",
            nombre: "LA MAQUINISTA",
            user: "lm056",
            password: "056lm",
            token: ""
        }, {
            code: "57",
            nombre: "ARTEA",
            user: "lm057",
            password: "057lm",
            token: ""
        }, {
            code: "58",
            nombre: "SEDE LEROY MERLIN",
            user: "lm058",
            password: "058lm",
            token: ""
        }, {
            code: "59",
            nombre: "CORDOBA",
            user: "lm059",
            password: "059lm",
            token: ""
        }, {
            code: "60",
            nombre: "TOLEDO",
            user: "lm060",
            password: "060lm",
            token: ""
        }, {
            code: "61",
            nombre: "MAJADAHONDA2",
            user: "lm061",
            password: "061lm",
            token: ""
        }, {
            code: "62",
            nombre: "ELCHE",
            user: "lm062",
            password: "062lm",
            token: ""
        }, {
            code: "63",
            nombre: "LA ZENIA",
            user: "lm063",
            password: "063lm",
            token: ""
        }, {
            code: "64",
            nombre: "VALLADOLID2",
            user: "lm064",
            password: "064lm",
            token: ""
        }, {
            code: "67",
            nombre: "SABADELL",
            user: "lm067",
            password: "067lm",
            token: ""
        }, {
            code: "68",
            nombre: "BADAJOZ",
            user: "lm068",
            password: "068lm",
            token: ""
        }, {
            code: "69",
            nombre: "LOGROÑO",
            user: "lm069",
            password: "069lm",
            token: ""
        }, {
            code: "70",
            nombre: "ALBACETE",
            user: "lm070",
            password: "070lm",
            token: ""
        }, {
            code: "71",
            nombre: "BURJASSOT",
            user: "lm071",
            password: "071lm",
            token: ""
        }, {
            code: "72",
            nombre: "HUELVA3",
            user: "lm072",
            password: "072lm",
            token: ""
        }, {
            code: "73",
            nombre: "SANT CUGAT",
            user: "lm073",
            password: "073lm",
            token: ""
        }, {
            code: "77",
            nombre: "IBIZA",
            user: "lm077",
            password: "077lm",
            token: ""
        }, {
            code: "78",
            nombre: "CEUTA",
            user: "lm078",
            password: "078lm",
            token: ""
        }, {
            code: "79",
            nombre: "FINESTRAT-BENIDORM",
            user: "lm079",
            password: "079lm",
            token: ""
        }, {
            code: "81",
            nombre: "LA CORUÑA",
            user: "lm081",
            password: "081lm",
            token: ""
        }, {
            code: "82",
            nombre: "VIGO",
            user: "lm082",
            password: "082lm",
            token: ""
        }, {
            code: "85",
            nombre: "SAN SEBASTIAN 2",
            user: "lm085",
            password: "085lm",
            token: ""
        }, {
            code: "89",
            nombre: "LLISA D'AMUNT",
            user: "lm089",
            password: "089lm",
            token: ""
        }, {
            code: "101",
            nombre: "SEVILLA TOMARES",
            user: "lm101",
            password: "101lm",
            token: ""
        }, {
            code: "102",
            nombre: "GRANADA ARMILLA 2",
            user: "lm102",
            password: "102lm",
            token: ""
        }, {
            code: "105",
            nombre: "MURCIA SUR",
            user: "lm105",
            password: "105lm",
            token: ""
        }, {
            code: "106",
            nombre: "SAGUNT",
            user: "lm106",
            password: "106lm",
            token: ""
        }, {
            code: "107",
            nombre: "ROQUETAS DE MAR",
            user: "lm107",
            password: "107lm",
            token: ""
        }, {
            code: "109",
            nombre: "NUEVOS MINISTERIOS",
            user: "lm109",
            password: "109lm",
            token: ""
        }, {
            code: "110",
            nombre: "CASTELLON",
            user: "lm110",
            password: "110lm",
            token: ""
        }, {
            code: "111",
            nombre: "LA ZENIA 2",
            user: "lm111",
            password: "111lm",
            token: ""
        }, {
            code: "114",
            nombre: "PZA.CATALUNYA",
            user: "lm114",
            password: "114lm",
            token: ""
        }, {
            code: "257",
            nombre: "COLMENAR",
            user: "lm257",
            password: "257lm",
            token: ""
        }, {
            code: "258",
            nombre: "TALAVERA",
            user: "lm258",
            password: "258lm",
            token: ""
        }, {
            code: "259",
            nombre: "FIGUERES",
            user: "lm259",
            password: "259lm",
            token: ""
        }, {
            code: "261",
            nombre: "ARANJUEZ",
            user: "lm261",
            password: "261lm",
            token: ""
        }, {
            code: "602",
            nombre: "LEPE",
            user: "lm602",
            password: "602lm",
            token: ""
        }, {
            code: "794",
            nombre: "MIJAS",
            user: "lm794",
            password: "794lm",
            token: ""
        }, {
            code: "954",
            nombre: "ONDARA",
            user: "lm954",
            password: "954lm",
            token: ""
        }, {
            code: "961",
            nombre: "MOS",
            user: "lm961",
            password: "961lm",
            token: ""
        }, {
            code: "947",
            nombre: "XATIVA",
            user: "lm947",
            password: "947lm",
            token: ""
        }, {
            code: "530",
            nombre: "OIARTZUN",
            user: "lm530",
            password: "530lm",
            token: ""
        }, {
            code: "756",
            nombre: "VILANOVA",
            user: "lm756",
            password: "756lm",
            token: ""
        }, {
            code: "9999",
            nombre: "TEST",
            user: "lmSMT",
            password: "SMTlm",
            token: ""
        }
    ];
};